pipeline {
    agent any 
    stages {
        stage('Hello') {
            steps {
                echo 'Hello Kaustubh' 
            }
        }
        stage ('code phase'){
            steps{
                input('Do you want to continue?')
            }
        }
        stage ('testing phase'){
             parallel{
                stage ('unit test'){
                    steps{
                        echo 'running unit test'
                    }
                }
             }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Run unit tests again' 
            }
        }
    }
}
